### PR TITLE
Various improvments

### PR DESCRIPTION
**Pull request by 0mp**
I'm testing rnt on FreeBSD 13-CURRENT at the moment and I stumbled upon a couple of problems.

### CODE REVIEW

**Comment by roman-neuhauser** [comment]
thanks a lot!

while the `local -r` change is noncontroversial, i'd prefer the `sed -f -` thing fixed in FreeBSD's sed.  i've seen environments so minimal they didn't have `/dev/std{in,out,err}`, and it looks like the fix is simple (the tests are more involved, i don't feel like studying those ATM):

```
diff --git a/usr.bin/sed/main.c b/usr.bin/sed/main.c
index 96994ec4469..66ca4d40c2a 100644
--- a/usr.bin/sed/main.c
+++ b/usr.bin/sed/main.c
@@ -236,9 +236,15 @@ cu_fgets(char *buf, int n, int *more)
                linenum = 0;
                switch (script->type) {
                case CU_FILE:
-                       if ((f = fopen(script->s, "r")) == NULL)
-                               err(1, "%s", script->s);
-                       fname = script->s;
+                       if (0 == strcmp(script->s, "-")) {
+                               if ((f = fdopen(STDIN_FILENO, "r")) == NULL)
+                                       err(1, "%s", "stdin");
+                               fname = "stdin";
+                       } else {
+                               if ((f = fopen(script->s, "r")) == NULL)
+                                       err(1, "%s", script->s);
+                               fname = script->s;
+                       }
                        state = ST_FILE;
                        goto again;
                case CU_STRING:
```

i'll see if i can get someone to bring it in, but i'm really rusty on the process.  i'll appreciate if you beat me to it. :)

**Comment by 0mp** [comment]
> while the `local -r` change is noncontroversial, 

Wonderful!

> i'd prefer the `sed -f -` thing fixed in FreeBSD's sed. i've seen environments so minimal they didn't have `/dev/std{in,out,err}`, and it looks like the fix is simple (the tests are more involved, i don't feel like studying those ATM):
> 
[snip]
> 
> i'll see if i can get someone to bring it in, but i'm really rusty on the process. i'll appreciate if you beat me to it. :)

I'll try to get it committed ;)

**Comment by 0mp** [comment]
Support has been committed in https://cgit.freebsd.org/src/commit/?id=f9ab72bb471a141f31a4476bb11bdaef81daf479

**Comment by roman-neuhauser** [comment]
i finally got around to pushing the `s/local -r/local/` change.  thx for your patience.

**Pull request closed without merging**
